//> using publish.organization "io.github.quafadas"
//> using publish.name "go-faster-skunk"
//> using publish.computeVersion "git:tag"
//> using publish.repository "central-s01"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/Quafadas/go-faster-skunk"
//> using publish.versionControl "github:Quafadas/go-faster-skunk"
//> using publish.developer "Simon Parten||https://github.com/Quafadas"
//> using publish.ci.computeVersion "git:tag"
//> using publish.ci.repository "central-s01"
//> using scala "3.2.2"
//> using platform "jvm"
//> using platform "scala-js"
//> using platform "scala-native"
//> using options "-Xmax-inlines", "300"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.ci.user "env:PUBLISH_USER"
//> using publish.ci.password "env:PUBLISH_PASSWORD"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
